### ISSUE TITLE
怎么这个下载下来后怎么生成exe文件？

### ISSUE THREAD

**Issue by leeseean** [UlyssesWu/Sinsy#2]
命令是什么？

**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by UlyssesWu** [comment]
Open `Sinsy.sln` in Visual Studio 2017 -> Press F6 (Build Solution)
