### ISSUE TITLE
Sinsy.exe -x dic -m nitech_jp_song070_f001.htsvoice -o song.wav song070_f001_063.xml  这个生成的音频声音怪怪的，断断续续，执行命令的时候提示no language，可能我要的是中文或者英文歌词，这个命令只处理日语，所以导致出来的音频断断续续不能曲调

### ISSUE THREAD

**Issue by leeseean** [UlyssesWu/Sinsy#4]
Sinsy.exe -x dic -m nitech_jp_song070_f001.htsvoice -o song.wav song070_f001_063.xml

这个生成的音频声音怪怪的，断断续续，执行命令的时候提示no language，可能我要的是中文或者英文歌词，这个命令只处理日语，所以导致出来的音频断断续续不能曲调

**Comment by UlyssesWu** [comment]
Already answered at https://github.com/VOICeVIO/Sinsy/issues/3#issuecomment-554634270

**Comment by UlyssesWu** [comment]
Short answer: The open-source version of Sinsy (by NIT) is Japanese only, but you can make a voice model and a dictionary to use it in other language. Do not ask me how to make them, it's not something easy. Just learn HTS / HMM by yourself.
